name: 库洛游戏

on:
  workflow_dispatch:
  schedule:
    - cron: "30 0 * * *"

env:
  TZ: Asia/Shanghai  # 设置时区为北京时间

jobs:
  Kuro-Sign:
    runs-on: ubuntu-latest

    steps:
      - name: Install Chinese Fonts
        run: sudo apt-get install -y fonts-wqy-microhei

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run App
        env:
          token: ${{ secrets.TOKEN }}
        run: node app.js

      - name: Git Commit
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          git add resources/sign.webp
          git commit -m "The servers have been updated✔ - $(TZ='Asia/Shanghai' date '+%Y-%m-%d %H:%M:%S')"
          git pull --rebase origin master
          git push origin master
